### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by Baldwinplayz** [K0R41/LolinS2MiniMarauderFlash#1]
The latest version of Maurader is not available here, also there is no support for updating in Mac os.

**Comment by phalkon13** [comment]
Honestly, I am surprised that they updated it to 0.11 as it is.
That being said, you can try to update via: https://esp.huhn.me/ online updater.
This website: https://github.com/justcallmekoko/ESP32Marauder/wiki/update-firmware#using-spacehuhn-web-updater
gives some great pointers on how to use that site.  From what I am seeing, this set of BINs has everything but the boot app.  That being said, as they have stated on the Amazon page, their board is custom built so it might not be the same parameter settings.

**Comment by K0R41** [comment]
The updater here is meant for the board that is sold online.
As there have been no feature additions in recent updates besides the GPS addition which the board does not support, I had chosen not to update it due to the amount of bugs in the recent versions.

That Being Said - I'll have a go at updating to the most recent version this weekend.

**Comment by Baldwinplayz** [comment]
Are there any updating instructions? The board I bought has a case that does not let me access the USB c.

**Comment by K0R41** [comment]
The top of the case is removable.

**Comment by Baldwinplayz** [comment]
The 3d printed black case it comes with can't be opened, it's completely sealed.

**Comment by K0R41** [comment]
It is not completely sealed.  Put your finger in the ridge on the side of it and lift the top off.

**Comment by Baldwinplayz** [comment]
Can it be placed back?
